const products = [
  { name: "Yerba Mate", price: 1500, stock: 500, section: "comestibles", active: true },
  { name: "Yerba Orgánica", price: 1500, stock: 500, section: "comestibles", active: true },
  { name: "Yerba Compuesta", price: 1500, stock: 500, section: "comestibles", active: true },
  { name: "Café", price: 1500, stock: 450, section: "comestibles", active: true },
  { name: "Té común", price: 1500, stock: 200, section: "comestibles", active: true },
  { name: "Té de hierbas", price: 1500, stock: 200, section: "comestibles", active: true },
  { name: "Té de manzanilla", price: 1500, stock: 200, section: "comestibles", active: true },
  { name: "Té de boldo", price: 1500, stock: 200, section: "comestibles", active: true },
  { name: "Mate Cocido", price: 1500, stock: 100, section: "comestibles", active: true },
  { name: "Azúcar", price: 1200, stock: 100, section: "comestibles", active: true },
  { name: "Dulce de leche", price: 1200, stock: 450, section: "comestibles", active: true },
  { name: "Galletitas", price: 1200, stock: 500, section: "comestibles", active: true },
  { name: "Aceite", price: 1200, stock: 100, section: "comestibles", active: false },
  { name: "Harina", price: 350, stock: 450, section: "comestibles", active: false },
  { name: "Manteca", price: 350, stock: 500, section: "comestibles", active: false },
  { name: "Mermelada de durazno", price: 350, stock: 450, section: "comestibles", active: false },
  { name: "Agua Mineral", price: 740, stock: 100, section: "bebidas", active: true },
  { name: "Vino", price: 740, stock: 50, section: "bebidas", active: true },
  { name: "Cerveza", price: 740, stock: 100, section: "bebidas", active: true },
  { name: "Gancia", price: 740, stock: 200, section: "bebidas", active: true },
  { name: "Fernet", price: 2300, stock: 100, section: "bebidas", active: true },
  { name: "Gaseosa", price: 2300, stock: 450, section: "bebidas", active: true },
  { name: "Leche", price: 2300, stock: 100, section: "comestibles", active: true },
  { name: "Crema", price: 2300, stock: 500, section: "comestibles", active: true },
  { name: "Yogur", price: 480, stock: 100, section: "comestibles", active: true },
  { name: "Queso Fresco", price: 1800, stock: 80, section: "comestibles", active: true },
  { name: "Pan Integral", price: 620, stock: 300, section: "comestibles", active: true },
  { name: "Mermelada de fresa", price: 950, stock: 200, section: "comestibles", active: true },
  { name: "Miel", price: 1400, stock: 120, section: "comestibles", active: true },
  { name: "Té verde", price: 1600, stock: 150, section: "comestibles", active: true }
];

module.exports = products;
